name: Build Plugin - Nightly Version

on: 
  push:
    branches:
      - master
    
jobs:
  build:
    name: Build from publish.hxml using LunaWizard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: lix-pm/setup-lix@1.0.0
      - run: lix download
      - run: npm ci
      - run: npm run build:publish
      - name: Archive nightly build
        uses: actions/upload-artifact@v2
        with:
          name: nightly
          path: dist
